#ifndef EDUBOX_ADDR_H
#define EDUBOX_ADDR_H

#define EDUBOX_ADDR_EDURGB              0x02
#define EDUBOX_ADDR_EDUBUTTON           0x04
#define EDUBOX_ADDR_EDUBUZZER           0x06
#define EDUBOX_ADDR_EDUPOTENTIOMETER    0x08
#define EDUBOX_ADDR_EDU7SEGMENT         0x0A
#define EDUBOX_ADDR_EDUDISTANCE         0x0C
#define EDUBOX_ADDR_EDULINEDETECTOR     0x0E
#define EDUBOX_ADDR_EDUSTEPPERMOTOR     0x10
#define EDUBOX_ADDR_EDUTEMPERATURE      0x12
#define EDUBOX_ADDR_EDUSERVO            0x14
#define EDUBOX_ADDR_EDUSWITCH           0x16
// #define EDUBOX_ADDR_EDUMOTIONSENSOR     0x18
#define EDUBOX_ADDR_EDUCOLORSENSOR      0x1A

#endif // EDUBOX_ADRESSES_H